import { type MetadataRoute } from 'next';
import { locales } from '@/i18n';

import { BASE_URL } from '@/lib/env';

export default function sitemap(): MetadataRoute.Sitemap {
  const sitemapRoutes: MetadataRoute.Sitemap = [
    {
      url: '',
      lastModified: new Date(),
      changeFrequency: 'daily',
      priority: 1,
    },
    {
      url: 'explore',
      lastModified: new Date(),
      changeFrequency: 'daily',
      priority: 0.8,
    },
    {
      url: 'submit',
      lastModified: new Date(),
      changeFrequency: 'monthly',
      priority: 0.8,
    },
  ];

  const s = ['undress-ai', 'ai-nude', 'porn-videos'];

  s.forEach((item) => {
    sitemapRoutes.push({
      url: item,
      lastModified: new Date(),
      changeFrequency: 'daily',
      priority: 0.8,
    });
  });

  const site = [
    '3movs-com',
    '4tube-com',
    'adultmagazine-net',
    'adultphotosets-best',
    'ai-nudes-app',
    'ainudes-io',
    'americass-net',
    'anyporn-com-categories-hd',
    'anysex-com',
    'astridai-co',
    'babesource-com',
    'bananamovies-org',
    'beautyai-fun:443-en-photo-face-swap',
    'bellesa-co',
    'bestporn4free-com',
    'bigbuttshub-com',
    'clothoff-io',
    'czechvideo-co',
    'deep-nudes-com',
    'deepswap-ai',
    'definebabe-com',
    'drawnudes-io',
    'drtuber-com',
    'empflix-com',
    'eporner-com',
    'eroticmv-com',
    'fapnado-com',
    'freeomovie-to',
    'fux-com',
    'galaxyporn-net',
    'hitprn-com',
    'hqporner-com',
    'hutporner-com',
    'iceporncasting-com',
    'imagefap-com',
    'jjgirls-com',
    'latestleaks-co',
    'letmejerk-com',
    'letsjerk-tv',
    'makenude-ai',
    'mangoporn-net',
    'netfapx-com',
    'netfapx-net',
    'newfaceporn-com',
    'nodress-io-undress',
    'nsfw-xxx',
    'nude-gals-com',
    'nude-modelz-com',
    'nudefusion-com-en',
    'nudify-me-partner-theporndude',
    'ok-xxx',
    'pandamovies-pw',
    'paradisehill-cc-porn',
    'pdude-link-cumlouder',
    'pdude-link-xvideos',
    'penly-ai-undress',
    'phub-at',
    'pics-x-com',
    'pimpandhost-com-site-trending',
    'pmatehunter-com',
    'porn2all-com',
    'porn4days-red',
    'porndig-com',
    'pornez-cam',
    'pornfake-net-home',
    'porngen-art-undress-ai',
    'porngo-com',
    'pornhat-com',
    'pornhd3x-tv',
    'pornhits-com-main',
    'pornobae-com',
    'pornone-com',
    'pornovideoshub-com',
    'pornseed-net',
    'porntop-com',
    'porntube-com',
    'pornvibe-org',
    'pornworks-ai-en-undress',
    'povaddict-com',
    'redd-tube-nsfw',
    'reddpics-com',
    'redtube-com',
    'severeporn-com',
    'sex-com-pins',
    'sextu-com',
    'sextvx-com',
    'sexygirlspics-com',
    'siska-video',
    'streamporn-pw',
    'swingerpornfun-com',
    'sxypix-com',
    'sxyprn-com',
    't-me-BraUndress_Entry_Bot',
    'taxi69-com',
    'thepornarea-com',
    'thepornfull-net',
    'titfap-com',
    'tnaflix-com',
    'trendyporn-com',
    'tube-perverzija-com',
    'tube8-com',
    'undress-app',
    'undress-cc',
    'undress-girl-com-en',
    'undress-love',
    'undress-xxx',
    'undress-zone-porndude',
    'undressai-com',
    'undressbaby-com',
    'undresser-ai',
    'undressher-app',
    'undressing-ai',
    'undressing-io',
    'undressninja-com',
    'usersporn-com',
    'veporn-com',
    'watchporn-to',
    'whatifapp-co-deepswap',
    'whoreshub-com',
    'x-pictures-io-aiporn',
    'xcafe-com',
    'xcum-com',
    'xfreehd-com',
    'xfuntaxy-com',
    'xhamster-com',
    'xhamster-com-photos',
    'xkeezmovies-com',
    'xmegadrive-com',
    'xmoviesforyou-com',
    'xnude-ai',
    'xnxx-com',
    'xozilla-com',
    'xtapes-to',
    'xxam-org',
    'xxvideoss-org',
    'xxxfiles-com',
    'xxxfree-watch',
    'xxxscenes-net',
    'xxxseed-com',
    'yesporn-vip',
    'yespornpleasexxx-com',
    'youjizz-com',
    'yourdailypornvideos-ws',
  ];

  site.forEach((item) => {
    sitemapRoutes.push({
      url: `ai/${item}`,
      lastModified: new Date(),
      changeFrequency: 'daily',
      priority: 0.8,
    });
  });

  const sitemapData = sitemapRoutes.flatMap((route) =>
    locales.map((locale) => {
      const lang = locale === 'en' ? '' : `/${locale}`;
      const routeUrl = route.url === '' ? '' : `/${route.url}`;
      return {
        ...route,
        url: `${BASE_URL}${lang}${routeUrl}`,
      };
    }),
  );

  return sitemapData;
}
